export const USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT';
  
export const FETCH_USERS_BEGIN = 'FETCH_USERS_BEGIN',
  FETCH_USERS_ERROR = 'FETCH_USERS_ERROR',
  FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
  
export const TOGGLE_NAVBAR_VISIBILITY = 'TOGGLE_NAVBAR_VISIBILITY';